version: '3.8'

services:
  flashtest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
    volumes:
      # Mount for development (optional)
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service with hot reload
  flashtest-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=development
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev